# Generated by Django 3.1 on 2020-08-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFDog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='purchase_status',
            field=models.CharField(default='False', max_length=25),
        ),
    ]
