# Generated by Django 3.1 on 2020-08-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFDog', '0002_shopitem_purchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.CharField(choices=[('pending', 'pending'), ('ready', 'ready'), ('complete', 'complete')], default='pending', max_length=20),
        ),
    ]
